name: Integration Test Linux

# Gets triggered on push and pull requests
on: [push, pull_request, workflow_dispatch]


jobs:
  # Single job to test the integration of vcpkg
  test_integration:
    name: Integration Test Linux
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Setting up CMake toolchain
      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1.12

      # Configuring CMake
      - name: Configure CMake
        run: cmake -S. -Bbuild 

      # Test building
      - name: Build
        run: cmake --build build
