name: Integration Test Windows

# Gets triggered on push and pull requests
on: [push, pull_request]

jobs:
  # Single job to test the integration of vcpkg
  test_integration:
    name: Integration Test Windows
    runs-on: windows-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Setup MSBuild
      - name: Setup MSBuild and add to PATH
        uses: microsoft/setup-msbuild@v1.0.2
        id: setup_msbuild

      # Setting up CMake toolchain
      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1.12

      # Configuring CMake
      - name: Configure CMake
        run: cmake -S. -Bbuild 

      # Test building
      - name: Build
        run: cmake --build build
